### PR TITLE
Add on_change option to run code in event of changes

### PR DESCRIPTION
**Pull request by abeverley**
The Augeas module is excellent, but it would be useful to know when changes to files have taken place and to action accordingly. This patch adds such an option.

### CODE REVIEW

**Comment by krimdomu** [comment]
Hi,

thank you for this patch. I'm going to merge it. Also i'm considering to merge this module into Rex core.

**Comment by abeverley** [comment]
Great, thanks for the quick turnaround.

It's not really a problem not being in core, I just thought it's the sort of thing that lots of people would use, and it's easier to spot if it's in core (I know it's in the documentation list, but I didn't realise it existed until my mailing list post).

Thanks!

**Comment by krimdomu** [comment]
This module is now merged into Rex core and will be available under Rex::Commands::Augeas

**Comment by abeverley** [comment]
Awesome, thank you.

**Pull request merged**
